.PHONY: all
all: help ## Prints this help message



.PHONY: test
test: ## Runs the test cases in the repository
	go test  ./... $(ARGS) | { grep -v 'no test files'; true; } | { grep -v 'no tests to run'; true; }



.PHONY: help
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'