on:
  push
name: make test
jobs:
  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version:  '^1.10.0'
      - run: go get golang.org/x/lint/golint
      - run: go get honnef.co/go/tools/cmd/staticcheck
      - name: make test
        run: make all
        shell: bash
      - name: Run Test Coverage
        run: make cover
      - run: bash <(curl -s https://codecov.io/bash)

